# Site settings
title: Extrowerk
header-img: img/home-bg.jpg
email: zmizsei@extrowerk.com
description: "My posts and thoughts"
baseurl: ""
url: "http://extrowerk.com"
#twitter_username: SBootstrap
#github_username:  davidtmiller
#facebook_username:  IronSummitMedia

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
